import { useCallback, useEffect, useRef, useState } from 'react'
import { listMessages, markMessagesRead, sendMessage, watchMessages, type ChatMessage } from '../lib/chat'
import { listMyTickets, openTicket, type SupportTicket } from '../lib/support'
import type { Trip } from '../lib/trips'

export function TripChat({ trip, userId, onClose }: { trip: Trip; userId: string; onClose: () => void }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [text, setText] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const end = useRef<HTMLDivElement>(null)
  const load = useCallback(async () => { try { setMessages(await listMessages(trip.id)); void markMessagesRead(trip.id); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo abrir el chat.') } }, [trip.id])
  useEffect(() => { queueMicrotask(() => void load()); return watchMessages(trip.id, () => void load()) }, [load, trip.id])
  useEffect(() => end.current?.scrollIntoView({ behavior: 'smooth' }), [messages])
  const submit = async () => { if (!text.trim()) return; setBusy(true); try { await sendMessage(trip.id, text); setText(''); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo enviar.') } finally { setBusy(false) } }
  return <div className="ride-dialog-backdrop"><section className="ride-chat"><header><div><small>CHAT DEL VIAJE</small><h2>{trip.conductorNombre ?? trip.pasajeroNombre}</h2></div><button onClick={onClose}>×</button></header><div className="ride-chat-messages">{messages.length === 0 && <p className="ride-chat-empty">Escribe solo lo necesario para coordinar este viaje.</p>}{messages.map((item) => <article key={item.id} className={item.authorId === userId ? 'mine' : ''}><p>{item.text}</p><small>{new Date(item.sentAt).toLocaleTimeString('es-EC', { hour: '2-digit', minute: '2-digit' })}</small></article>)}<div ref={end}/></div>{error && <p className="ride-extra-error">{error}</p>}<footer><textarea maxLength={500} value={text} onChange={(event) => setText(event.target.value)} placeholder="Escribe un mensaje…"/><button disabled={busy || !text.trim()} onClick={() => void submit()}>Enviar</button></footer></section></div>
}

export function SupportPage({ userId, trips }: { userId: string; trips: Trip[] }) {
  const [tickets, setTickets] = useState<SupportTicket[]>([]); const [subject, setSubject] = useState(''); const [message, setMessage] = useState(''); const [category, setCategory] = useState('viaje'); const [tripId, setTripId] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { try { setTickets(await listMyTickets(userId)); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cargar soporte.') } }, [userId])
  useEffect(() => { queueMicrotask(() => void load()) }, [load])
  const submit = async () => { setBusy(true); try { await openTicket(subject, message, category, tripId || undefined); setSubject(''); setMessage(''); setTripId(''); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo abrir el caso.') } finally { setBusy(false) } }
  return <div className="passenger-page support-page"><section className="passenger-section-head"><div><span>AYUDA REAL</span><h2>Soporte</h2><p>Cuéntanos qué ocurrió y podrás seguir la respuesta desde aquí.</p></div></section><div className="support-layout"><section className="support-form"><label>Categoría<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="viaje">Un viaje</option><option value="pago">Un cobro</option><option value="cuenta">Mi cuenta</option><option value="conductor">Ser conductor</option><option value="otro">Otra cosa</option></select></label><label>Viaje relacionado<select value={tripId} onChange={(event) => setTripId(event.target.value)}><option value="">Ninguno</option>{trips.map((trip) => <option value={trip.id} key={trip.id}>{trip.destinoTexto}</option>)}</select></label><label>Asunto<input maxLength={100} value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="Resume el problema"/></label><label>¿Qué ocurrió?<textarea maxLength={1200} value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Incluye los detalles que nos ayuden a resolverlo"/></label>{error && <p className="ride-extra-error">{error}</p>}<button disabled={busy || subject.trim().length < 3 || message.trim().length < 10} onClick={() => void submit()}>{busy ? 'Enviando…' : 'Abrir caso'}</button></section><section className="support-list">{tickets.length === 0 ? <p>No tienes casos abiertos.</p> : tickets.map((ticket) => <article key={ticket.id}><header><span>{ticket.category}</span><b>{ticket.status.replace('_', ' ')}</b></header><h3>{ticket.subject}</h3><p>{ticket.message}</p>{ticket.answer && <blockquote><small>RESPUESTA DE RIDE</small>{ticket.answer}</blockquote>}</article>)}</section></div></div>
}
